"""Sizing the 4-thruster design: sweep duct, stem, ring and slot sizes with
the same fan and motor as AIRFLOW.md, 4 thrusters each carrying Q/4.
Writes AIRFLOW-4T.md."""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import airflow as a  # noqa: E402

M = a.MOTORS["2207 1750KV, 4S"]
_solve = a.solve


def run(n, duct, stem, slot, slot_r):
    a.N_THR, a.DUCT_D, a.SLOT_R = n, duct / 1000, slot_r / 1000
    a.solve = lambda p_air, slot_w, duct_d=None, stem_d=None, phi=a.PHI_AUG: _solve(
        p_air, slot_w, duct_d=a.DUCT_D, stem_d=stem_d, phi=phi)
    r = a.solve_motor(M, slot / 1000, stem / 1000)
    a.solve = _solve
    return r


def main():
    out = []
    w = out.append
    base = run(8, 24, 22, 1.6, 22.0)
    w("# Airflow: the 4-thruster design\n")
    w("Generated by `airflow_4t.py`, with the same fan, motor and loss model as [AIRFLOW.md](AIRFLOW.md).\n")
    w("With 4 thrusters instead of 8, each duct, stem and ring carries twice the flow. Keeping the air speeds the same needs twice the area:")
    w("- duct bore Ø24 → **Ø34 mm**")
    w("- stem bore Ø22 → **Ø31 mm**")
    w("- a wider slot, on a slightly larger ring\n")
    w(f"8-thruster reference: **{base['thrust'] / 9.81e-3:.0f} gf** (duct Ø24, stem Ø22, slot 1.6 mm on a 22 mm lip radius).\n")
    w("| Duct Ø | Stem bore Ø | Slot lip radius | Slot | Thrust | Duct speed | Limited by |")
    w("|---|---|---|---|---|---|---|")
    for duct, stem, sr, slot in ((24, 22, 22.0, 1.6), (24, 22, 22.0, 2.4), (30, 28, 26.0, 2.0),
                                 (34, 31, 22.0, 2.4), (34, 31, 25.0, 1.6), (34, 31, 25.0, 2.0),
                                 (34, 31, 25.0, 2.4), (34, 31, 31.0, 1.6)):
        r = run(4, duct, stem, slot, sr)
        mark = " ← built" if (duct, stem, sr, slot) == (34, 31, 25.0, 2.0) else ""
        w(f"| {duct} mm | {stem} mm | {sr:.0f} mm | {slot} mm | **{r['thrust'] / 9.81e-3:.0f} gf**{mark} | "
          f"{r['v_d']:.1f} m/s | {r['limit']} |")
    w("")
    w("- **Keeping the 8-thruster ducts (Ø24) with only 4 thrusters loses about a fifth of the thrust.** Each duct would carry twice the flow at twice the speed, so its losses would be four times higher.")
    w("- **With the ducts and stems scaled up, 4 thrusters make slightly more thrust than 8** (about +3%). There are fewer, larger passages with less wall friction.")
    w("- **Built:**")
    w("  - duct Ø34, stem Ø34/31")
    w("  - ring with the 8-thruster ring's profile (32 mm tall, 12 mm between throat and outer wall), on a 22.5 mm throat with a 3.5 mm Coanda lip and a 2.0 mm slot (25 mm slot radius)")
    w("  - the Ø31 stem bore reshapes into an oval port of the same area where it enters the ring, so the ring can stay 32 mm tall")
    w("  - 44-tooth gears to clear the wider stem")
    w("  - a housing ceiling 10 mm higher, so the Ø34 duct mouths fit under it")
    open(os.path.join(HERE, "AIRFLOW-4T.md"), "w").write("\n".join(out) + "\n")
    print("\n".join(out))


if __name__ == "__main__":
    main()
