"""How close is each design to floating? Mass budget against hydrogen lift
and fan thrust, for the 8- and 4-thruster designs at bench size (x1) and at
Kobra Max size (x1.9), and for the self-contained double-Kobra build (x3.8,
12 slices printed in pieces, battery and controller on board), in standard
and lightweight (foaming) PLA.
Writes FLOAT.md. Geometry comes from hull_volumes.py (run per variant)."""
import json
import math
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

NET_LIFT = 1.204 - 0.0838          # g per litre: air minus hydrogen, 20 C, sea level
MATERIALS = {"PLA": 1.24, "LW-PLA, moderate foam": 0.80, "LW-PLA, full foam": 0.60}
PLA, PETG = 1.24, 1.27
FILM_GSM = 11.0                    # 12 um LDPE film, g/m2
CONFIGS = [("8T", 1.0), ("4T", 1.0), ("8T", 1.9), ("4T", 1.9)]
BIG = dict(OAS_VARIANT="4T", OAS_SCALE="3.8", OAS_SLICES="12", OAS_THRUSTER="S", OAS_PIECES="1", OAS_RIB="1.2")
# self-contained: electronics on board (grams) and battery options (grams, Wh)
ONBOARD = {"ESC 30 A (the fan peaks at ~25 A)": 7.0, "ESP32 board (drives servos and ESC directly)": 8.0, "3 A BEC": 6.0,
           "IMU + barometer": 4.0, "switch, connectors, wiring": 25.0}
BATTERIES = [("4S LiPo 1500 mAh", 180.0, 22.2), ("4S 18650 Li-ion 1P (Molicel P28A)", 195.0, 41.4),
             ("4S 21700 Li-ion 1P (Molicel P45B)", 300.0, 64.8)]
FAN_W_MAX = 25.0 * 14.8            # electrical power at full fan thrust
MANOEUVRE_W, AVIONICS_W = 20.0, 4.0


def geometry(variant, scale, extra=None):
    env = dict(os.environ, OAS_VARIANT=variant, OAS_SCALE=str(scale), **(extra or {}))
    out = subprocess.run([sys.executable, os.path.join(HERE, "hull_volumes.py")], env=env,
                         capture_output=True, text=True, check=True).stdout
    return json.loads(out.strip().splitlines()[-1])


def thrust_gf(g):
    """Fan thrust (all jets down) from the airflow model, with this variant's
    duct, stem and slot sizes and its (scaled) duct length."""
    import airflow as a
    a.N_THR, a.DUCT_D, a.SLOT_R, a.DUCT_L = g["n_thr"], g["duct_d"] / 1000, g["slot_r"] / 1000, g["duct_l"]
    orig = a.solve
    a.solve = lambda p_air, slot_w, duct_d=None, stem_d=None, phi=a.PHI_AUG: orig(
        p_air, slot_w, duct_d=a.DUCT_D, stem_d=stem_d, phi=phi)
    r = a.solve_motor(a.MOTORS["2207 1750KV, 4S"], g["slot"] / 1000, g["stem_id"] / 1000)
    a.solve = orig
    return r["thrust"] / 9.81e-3


def budget(g, rho_lw):
    """Airborne mass (g) of the tethered model: battery, ESC and controller stay on the bench."""
    n, pt = g["n_thr"], g["parts"]
    s = g["scale"]
    printed = {
        "hull (%d slices)" % g.get("n_slices", 8): g["hull_cm3"] * rho_lw,
        **({"intake tubes": g["tubes_cm3"] * rho_lw, "avionics tray": pt["avionics_tray"] * rho_lw}
           if g.get("pieces") else {}),
        "thruster rings": n * pt["thruster_ring"] * rho_lw,
        "servo mounts": n * pt["servo_mount"] * rho_lw,
        "stems and gears (PLA)": n * (pt["stem"] + pt["stem_gear"] + pt["servo_gear"]) * PLA,
        "fan hatch (PLA)": pt["fan_hatch"] * PLA,
        "impeller (PETG)": pt["impeller"] * PETG,
    }
    hardware = {
        "2207 motor": 32.0,
        **({f"{n} x SG90 servos (9 g; the rings need little torque)": 9.0 * n} if g.get("pieces")
           else {f"{n} x MG90S servos": 13.4 * n}),
        "wiring": 5.0 + 2.5 * n * s,
        "screws": 3.0,
        # epoxy on the airtight seams (duct halves, housing ring), thin CA on the lattice seams
        "glue": 4.5 * (2 * n * g["duct_l"] + 2 * 2 * math.pi * 0.08)
                + 0.8 * (g.get("n_slices", 8) * g.get("meridian", 0.45 * s) + g.get("cuts", 0.0)),
        "gas cells (12 um LDPE)": 1.3 * g["surface_m2"] * FILM_GSM,
    }
    return printed, hardware


def main():
    geos = [geometry(v, s) for v, s in CONFIGS]
    big = geometry("4T", 3.8, {k: v for k, v in BIG.items() if k not in ("OAS_VARIANT", "OAS_SCALE")})
    out = []
    w = out.append
    w("# Will it float? Mass, hydrogen lift and fan thrust\n")
    w("Generated by `float_budget.py` from the current CAD (every volume comes from a tessellated STEP). Rerun it after changing the model.\n")
    w("**Assumptions**")
    w(f"- **Hydrogen:** net lift {NET_LIFT:.2f} g per litre (20 °C, sea level). The gas cells fill all the free space inside the skin, outside the shaft, fan housing and ducts.")
    w(f"- **Gas cells:** 12 µm LDPE film ({FILM_GSM:.0f} g/m²), 1.3 × the hull's surface area.")
    w("- **Materials:**")
    w("  - Hull, thruster rings and servo mounts are printed in the material shown.")
    w("  - Stems, gears and the fan hatch stay standard PLA (1.24 g/cm³); the impeller is PETG.")
    w("  - Lightweight (foaming) PLA: 0.80 g/cm³ with moderate foam, 0.60 with full foam.")
    w("- **Airborne mass:** tethered, so the battery, ESC and controller stay on the bench.")
    w("- **Thrust:** the fan's full thrust with every jet pointing down, from the airflow model (2207 1750 KV on 4S, shrouded fan). The same fan at every size.")
    w("- **x1.9 (Kobra Max):** only the hull grows. Walls, ribs, fan, ducts, thrusters and servos keep their size.\n")
    w("| Design | Size | Hull material | Airborne mass | H₂ volume | H₂ lift | Lift ÷ mass | Fan thrust | Lift + thrust − mass |")
    w("|---|---|---|---|---|---|---|---|---|")
    rows = []
    for g in geos:
        t = thrust_gf(g)
        for mat, rho in MATERIALS.items():
            printed, hw = budget(g, rho)
            mass = sum(printed.values()) + sum(hw.values())
            lift = g["v_free"] * NET_LIFT
            size = "bench, 415 mm" if g["scale"] == 1 else f"Kobra Max x{g['scale']:g}, {2 * g['A']:.0f} mm"
            name = "8 thrusters" if g["n_thr"] == 8 else "4 thrusters"
            margin = lift + t - mass
            rows.append((name, size, mat, mass, lift, t, margin, printed, hw, g))
            w(f"| {name} | {size} | {mat} | {mass:.0f} g | {g['v_free']:.1f} L | {lift:.0f} g | "
              f"**{100 * lift / mass:.0f}%** | {t:.0f} gf | {margin:+.0f} g{' ✅ hovers' if margin > 0 else ''} |")
    w("")
    w("- **Lift ÷ mass:** how close the hydrogen alone is to floating the model. 100% means it floats with no fan.")
    w("- **Lift + thrust − mass:** positive means the fan plus the hydrogen can hold the model up, while the fan runs.\n")

    # break-even size for pure buoyancy, 4T in LW-PLA
    w("## How big would it have to be to float on hydrogen alone?\n")
    w("Lift grows with size³. The thin-walled hull grows much more slowly, because its walls and ribs keep their thickness (measured below between x1 and x1.9). The fan, servos and wiring stay the same.\n")
    w("| Design | Hull material | Floats at scale | Hull diameter |")
    w("|---|---|---|---|")
    for g1, g2 in ((geos[0], geos[2]), (geos[1], geos[3])):
        for mat in ("LW-PLA, moderate foam", "LW-PLA, full foam"):
            rho = MATERIALS[mat]
            h1, h2 = g1["hull_cm3"] * rho, g2["hull_cm3"] * rho
            k = math.log(h2 / h1) / math.log(g2["scale"])        # measured: hull mass ~ S^k
            b = (g2["v_free"] - g1["v_free"]) / (g2["scale"] ** 3 - 1)
            c = b - g1["v_free"]                                  # free volume ~ b S^3 - c

            def mass(s):
                g = dict(g1, scale=s, surface_m2=g1["surface_m2"] * s * s)
                pr, hw = budget(g, rho)
                return h1 * s ** k + sum(pr.values()) - next(v for k_, v in pr.items() if k_.startswith("hull (")) + sum(hw.values())
            s = 1.0
            while NET_LIFT * (b * s ** 3 - c) < mass(s):
                s += 0.01
            name = "8 thrusters" if g1["n_thr"] == 8 else "4 thrusters"
            w(f"| {name} | {mat} | x{s:.1f} (hull mass grows as S^{k:.2f}) | {2 * g1['A'] * s / 1000:.1f} m |")
    w("")
    w("These keep today's 0.86 mm walls and 2 mm ribs. A real hull that size would need thicker ribs, or a frame and fabric envelope instead of a printed skin, so treat them as lower bounds.\n")

    # self-contained double-Kobra build
    t_big = thrust_gf(big)
    w("## Self-contained: double Kobra size (x3.8, 1.58 m), battery and controller on board\n")
    w(f"4 thrusters on 12 slices, with the lightest printable lattice (1.2 mm webs). Each slice prints on a Kobra Max in 5 pieces, and the intake is two printed tubes. The thruster hardware is the 8-thruster size (Ø24 ducts), which keeps the duct walls light and still gives {t_big:.0f} gf. The fan is unchanged. The ESC, ESP32, BEC, IMU and battery are on board, on the avionics tray just above the fan housing.\n")
    w(f"Hydrogen: {big['v_free']:.0f} L, lifting **{big['v_free'] * NET_LIFT:.0f} g**.\n")
    w("| Hull material | Airframe | + electronics | Battery | Total | H₂ lift − total | Fan needed to hold height | Flight time |")
    w("|---|---|---|---|---|---|---|---|")
    onboard = sum(ONBOARD.values())
    lift = big["v_free"] * NET_LIFT
    best = None
    for mat in ("LW-PLA, moderate foam", "LW-PLA, full foam"):
        pr, hw = budget(big, MATERIALS[mat])
        frame = sum(pr.values()) + sum(hw.values())
        for bname, bg, wh in BATTERIES:
            total = frame + onboard + bg
            margin = lift - total
            deficit = max(0.0, -margin)
            if deficit > t_big:
                need, time_ = "more than the fan can give", "—"
            else:
                p_hold = FAN_W_MAX * (deficit / t_big) ** 1.5
                watts = p_hold + MANOEUVRE_W + AVIONICS_W
                need = f"{p_hold:.0f} W" if deficit else "none: floats"
                time_ = f"{0.8 * wh / watts * 60:.0f} min"
            w(f"| {mat} | {frame:.0f} g | {onboard:.0f} g | {bname}, {bg:.0f} g | {total:.0f} g | "
              f"**{margin:+.0f} g** | {need} | {time_} |")
            if best is None or margin > best[0]:
                best = (margin, mat, bname, pr, hw, total)
    w("")
    w(f"- **Flight time** uses 80% of the battery. It counts {MANOEUVRE_W:.0f} W average for manoeuvring and {AVIONICS_W:.0f} W for the servos and electronics, plus the fan power needed to hold height when the ship is heavier than its lift.")
    w(f"- **Fan power to hold height:** full thrust ({t_big:.0f} gf) takes about {FAN_W_MAX:.0f} W. Thrust grows as power^(2/3), so holding up a shortfall of W grams takes {FAN_W_MAX:.0f} W × (W / {t_big:.0f})^1.5.")
    w("- **Too light is fine:** a ship lighter than its lift is trimmed with a few grams of ballast, or by filling the gas cells less.\n")
    margin, mat, bname, pr, hw, total = best
    w(f"### Mass breakdown: {mat}, {bname}\n")
    w("| Item | g |")
    w("|---|---|")
    for k_, v in list(pr.items()) + list(hw.items()) + list(ONBOARD.items()):
        w(f"| {k_} | {v:.0f} |")
    w(f"| battery ({bname}) | {[b for b in BATTERIES if b[0] == bname][0][1]:.0f} |")
    w(f"| **Total** | **{total:.0f}** |")
    w(f"| **Hydrogen lift** | **{lift:.0f}** |\n")

    # details for the headline design
    w("## Mass breakdown: 4 thrusters, Kobra Max x1.9, LW-PLA moderate foam\n")
    for name, size, mat, mass, lift, t, margin, printed, hw, g in rows:
        if name == "4 thrusters" and g["scale"] != 1 and mat == "LW-PLA, moderate foam":
            w("| Item | g |")
            w("|---|---|")
            for k_, v in list(printed.items()) + list(hw.items()):
                w(f"| {k_} | {v:.0f} |")
            w(f"| **Total** | **{mass:.0f}** |")
    open(os.path.join(HERE, "FLOAT.md"), "w").write("\n".join(out) + "\n")
    print("\n".join(out))


if __name__ == "__main__":
    main()
