"""How close is each design to floating? Mass budget against hydrogen lift
and fan thrust, for the 8- and 4-thruster designs at bench size (x1) and at
Kobra Max size (x1.9), in standard and lightweight (foaming) PLA.
Writes FLOAT.md. Geometry comes from hull_volumes.py (run per variant)."""
import json
import math
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

NET_LIFT = 1.204 - 0.0838          # g per litre: air minus hydrogen, 20 C, sea level
MATERIALS = {"PLA": 1.24, "LW-PLA, moderate foam": 0.80, "LW-PLA, full foam": 0.60}
PLA, PETG = 1.24, 1.27
FILM_GSM = 11.0                    # 12 um LDPE film, g/m2
CONFIGS = [("8T", 1.0), ("4T", 1.0), ("8T", 1.9), ("4T", 1.9)]


def geometry(variant, scale):
    env = dict(os.environ, OAS_VARIANT=variant, OAS_SCALE=str(scale))
    out = subprocess.run([sys.executable, os.path.join(HERE, "hull_volumes.py")], env=env,
                         capture_output=True, text=True, check=True).stdout
    return json.loads(out.strip().splitlines()[-1])


def thrust_gf(g):
    """Fan thrust (all jets down) from the airflow model, with this variant's
    duct, stem and slot sizes and its (scaled) duct length."""
    import airflow as a
    a.N_THR, a.DUCT_D, a.SLOT_R, a.DUCT_L = g["n_thr"], g["duct_d"] / 1000, g["slot_r"] / 1000, g["duct_l"]
    orig = a.solve
    a.solve = lambda p_air, slot_w, duct_d=None, stem_d=None, phi=a.PHI_AUG: orig(
        p_air, slot_w, duct_d=a.DUCT_D, stem_d=stem_d, phi=phi)
    r = a.solve_motor(a.MOTORS["2207 1750KV, 4S"], g["slot"] / 1000, g["stem_id"] / 1000)
    a.solve = orig
    return r["thrust"] / 9.81e-3


def budget(g, rho_lw):
    """Airborne mass (g) of the tethered model: battery, ESC and controller stay on the bench."""
    n, pt = g["n_thr"], g["parts"]
    s = g["scale"]
    printed = {
        "hull (8 slices)": g["hull_cm3"] * rho_lw,
        "thruster rings": n * pt["thruster_ring"] * rho_lw,
        "servo mounts": n * pt["servo_mount"] * rho_lw,
        "stems and gears (PLA)": n * (pt["stem"] + pt["stem_gear"] + pt["servo_gear"]) * PLA,
        "fan hatch (PLA)": pt["fan_hatch"] * PLA,
        "impeller (PETG)": pt["impeller"] * PETG,
    }
    hardware = {
        "2207 motor": 32.0,
        f"{n} x MG90S servos": 13.4 * n,
        "wiring": 5.0 + 2.5 * n * s,
        "screws": 3.0,
        "epoxy and tape": 15.0 * s ** 2,
        "gas cells (12 um LDPE)": 1.3 * g["surface_m2"] * FILM_GSM,
    }
    return printed, hardware


def main():
    geos = [geometry(v, s) for v, s in CONFIGS]
    out = []
    w = out.append
    w("# Will it float? Mass, hydrogen lift and fan thrust\n")
    w("Generated by `float_budget.py` from the current CAD (every volume comes from a tessellated STEP). Rerun it after changing the model.\n")
    w("**Assumptions**")
    w(f"- **Hydrogen:** net lift {NET_LIFT:.2f} g per litre (20 °C, sea level). The gas cells fill all the free space inside the skin, outside the shaft, fan housing and ducts.")
    w(f"- **Gas cells:** 12 µm LDPE film ({FILM_GSM:.0f} g/m²), 1.3 × the hull's surface area.")
    w("- **Materials:**")
    w("  - Hull, thruster rings and servo mounts are printed in the material shown.")
    w("  - Stems, gears and the fan hatch stay standard PLA (1.24 g/cm³); the impeller is PETG.")
    w("  - Lightweight (foaming) PLA: 0.80 g/cm³ with moderate foam, 0.60 with full foam.")
    w("- **Airborne mass:** tethered, so the battery, ESC and controller stay on the bench.")
    w("- **Thrust:** the fan's full thrust with every jet pointing down, from the airflow model (2207 1750 KV on 4S, shrouded fan). The same fan at every size.")
    w("- **x1.9 (Kobra Max):** only the hull grows. Walls, ribs, fan, ducts, thrusters and servos keep their size.\n")
    w("| Design | Size | Hull material | Airborne mass | H₂ volume | H₂ lift | Lift ÷ mass | Fan thrust | Lift + thrust − mass |")
    w("|---|---|---|---|---|---|---|---|---|")
    rows = []
    for g in geos:
        t = thrust_gf(g)
        for mat, rho in MATERIALS.items():
            printed, hw = budget(g, rho)
            mass = sum(printed.values()) + sum(hw.values())
            lift = g["v_free"] * NET_LIFT
            size = "bench, 415 mm" if g["scale"] == 1 else f"Kobra Max x{g['scale']:g}, {2 * g['A']:.0f} mm"
            name = "8 thrusters" if g["n_thr"] == 8 else "4 thrusters"
            margin = lift + t - mass
            rows.append((name, size, mat, mass, lift, t, margin, printed, hw, g))
            w(f"| {name} | {size} | {mat} | {mass:.0f} g | {g['v_free']:.1f} L | {lift:.0f} g | "
              f"**{100 * lift / mass:.0f}%** | {t:.0f} gf | {margin:+.0f} g{' ✅ hovers' if margin > 0 else ''} |")
    w("")
    w("- **Lift ÷ mass:** how close the hydrogen alone is to floating the model. 100% means it floats with no fan.")
    w("- **Lift + thrust − mass:** positive means the fan plus the hydrogen can hold the model up, while the fan runs.\n")

    # break-even size for pure buoyancy, 4T in LW-PLA
    w("## How big would it have to be to float on hydrogen alone?\n")
    w("Lift grows with size³. The thin-walled hull grows much more slowly, because its walls and ribs keep their thickness (measured below between x1 and x1.9). The fan, servos and wiring stay the same.\n")
    w("| Design | Hull material | Floats at scale | Hull diameter |")
    w("|---|---|---|---|")
    for g1, g2 in ((geos[0], geos[2]), (geos[1], geos[3])):
        for mat in ("LW-PLA, moderate foam", "LW-PLA, full foam"):
            rho = MATERIALS[mat]
            h1, h2 = g1["hull_cm3"] * rho, g2["hull_cm3"] * rho
            k = math.log(h2 / h1) / math.log(g2["scale"])        # measured: hull mass ~ S^k
            b = (g2["v_free"] - g1["v_free"]) / (g2["scale"] ** 3 - 1)
            c = b - g1["v_free"]                                  # free volume ~ b S^3 - c

            def mass(s):
                g = dict(g1, scale=s, surface_m2=g1["surface_m2"] * s * s)
                pr, hw = budget(g, rho)
                return h1 * s ** k + sum(pr.values()) - pr["hull (8 slices)"] + sum(hw.values())
            s = 1.0
            while NET_LIFT * (b * s ** 3 - c) < mass(s):
                s += 0.01
            name = "8 thrusters" if g1["n_thr"] == 8 else "4 thrusters"
            w(f"| {name} | {mat} | x{s:.1f} (hull mass grows as S^{k:.2f}) | {2 * g1['A'] * s / 1000:.1f} m |")
    w("")
    w("These keep today's 0.86 mm walls and 2 mm ribs. A real hull that size would need thicker ribs, or a frame and fabric envelope instead of a printed skin, so treat them as lower bounds.\n")

    # details for the headline design
    w("## Mass breakdown: 4 thrusters, Kobra Max x1.9, LW-PLA moderate foam\n")
    for name, size, mat, mass, lift, t, margin, printed, hw, g in rows:
        if name == "4 thrusters" and g["scale"] != 1 and mat == "LW-PLA, moderate foam":
            w("| Item | g |")
            w("|---|---|")
            for k_, v in list(printed.items()) + list(hw.items()):
                w(f"| {k_} | {v:.0f} |")
            w(f"| **Total** | **{mass:.0f}** |")
    open(os.path.join(HERE, "FLOAT.md"), "w").write("\n".join(out) + "\n")
    print("\n".join(out))


if __name__ == "__main__":
    main()
